baseurl = "https://jasik.xyz"
languageCode = "en"
title = "Bowl of TARDIS"

copyright = "Caleb Jasik 2018-2020"

MetaDataFormat = "toml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

enableRobotsTXT = true

enableGitInfo = true

pygmentsUseClasses = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
title = "Bowl of TARDIS"
description = "Bowl of TARDIS is the space for Caleb Jasik on the web. Mostly random blog posts, and occasional pictures"
images = ["uploads/cool-octopus.jpg"]


[author]
name = "Caleb Jasik"
homepage = "https://jasik.xyz"
email = "calebjasik@jasik.xyz"

[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.extensions]
typographer = false
[markup.goldmark.renderer]
unsafe = true

[imaging]
quality = 75

[privacy]
[privacy.instagram]
simple = true
[privacy.twitter]
simple = true
[privacy.vimeo]
simple = true
[privacy.youtube]
privacyEnhanced = true

[services]
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true

[outputs]
home = ["HTML", "RSS", "HEADERS"]

[mediaTypes]
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

[outputFormats]
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
