site_url: "https://jasik.xyz"
logo_url: "https://jasik.xyz/logo.svg"
backend:
  name: git-gateway
  branch: main # branch to update; optional defaults to main
publish_mode: editorial_workflow
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: posts
    label: Posts
    label_singular: "Post"
    folder: content/
    path: "{{slug}}/index"
    preview_path: "/{{slug}}"
    media_folder: ""
    public_folder: ""
    format: toml-frontmatter
    filter: { field: "Type", value: "post" }
    nested:
      depth: 100 # max depth to show in the collection tree
    create: true
    fields:
      - { label: "Title", name: "Title", widget: "string", required: false }
      - { label: "Date", name: "Date", widget: "datetime" }
      - {
          label: "Description",
          name: "Description",
          widget: "string",
          required: false,
        }
      - {
          label: "Type",
          name: "Type",
          widget: "select",
          default: "post",
          options: ["post", "note", "photo"],
        }
      - {
          label: "Draft",
          name: "Draft",
          widget: "boolean",
          required: false,
          default: true,
        }
      - {
          label: "isMath",
          name: "isMath",
          widget: "boolean",
          required: false,
          default: false,
        }
      - { label: "Img Alt", name: "ImgAlt", widget: "text", required: false }
      - { label: "Slug", name: "Slug", widget: "string", required: false }
      - {
          label: "Tags",
          name: "Tags",
          widget: "list",
          label_singular: "Tag",
          required: false,
        }
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          label_singular: "Category",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: notes
    label: Notes
    label_singular: "Note"
    identifier_field: "Date"
    folder: content/
    path: "{{ slug }}/index"
    preview_path: "/{{slug}}"
    media_folder: ""
    public_folder: ""
    format: toml-frontmatter
    filter: { field: "Type", value: "note" }
    create: true
    fields:
      - { label: Title, name: "Title", widget: "string", required: false }
      - {
          label: Type,
          name: "Type",
          widget: "select",
          default: note,
          options: ["post", "note", "photo"],
        }
      - { label: "Draft", name: "Draft", widget: "boolean", default: true }
      - { label: Date, name: "Date", widget: "datetime" }
      - { label: "Img Alt", name: "ImgAlt", widget: "text", required: false }
      - {
          label: "Tags",
          name: "Tags",
          widget: "list",
          label_singular: "Tag",
          required: false,
        }
      - {
          label: "Categories",
          name: "Categories",
          widget: "list",
          label_singular: "Category",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: photos
    label: Photos
    label_singular: "Photo"
    folder: content/photos/
    path: "{{ slug }}/index"
    preview_path: "/photos/{{slug}}"
    media_folder: ""
    public_folder: ""
    create: true
    format: toml-frontmatter
    fields:
      - { label: Title, name: "Title", widget: "string" }
      - {
          label: Type,
          name: "Type",
          widget: "select",
          default: "photo",
          options: ["post", "note", "photo"],
        }
      - { label: "Draft", name: "Draft", widget: "boolean", default: true }
      - { label: Date, name: "Date", widget: "datetime" }
      - { label: "Img Alt", name: "ImgAlt", widget: "text", required: false }
      - {
          label: "Tags",
          name: "Tags",
          widget: "list",
          label_singular: "Tag",
          required: false,
        }
      - {
          label: "Categories",
          name: "Categories",
          widget: "list",
          label_singular: "Category",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "standalone pages"
    label: Standalone Pages
    files:
      - label: "Pay"
        name: "pay"
        file: "content/pay/_index.md"
        format: toml-frontmatter
        fields:
          - { label: "Title", name: "Title", widget: "string" }
          - { label: "Slug", name: "Slug", widget: "string" }
          - { label: "Type", name: "Type", widget: "string" }
          - {
              label: "Description",
              name: "Description",
              widget: "string",
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Portfolio"
        name: "portfolio"
        file: "content/portfolio/_index.md"
        format: toml-frontmatter
        fields:
          - { label: "Title", name: "Title", widget: "string" }
          - { label: "Slug", name: "Slug", widget: "string" }
          - { label: "Type", name: "Type", widget: "string" }
          - {
              label: "Description",
              name: "Description",
              widget: "string",
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
