name: Broken Link Check

on:
  schedule:
    - cron: 0 0 1 * * # run monthly
  repository_dispatch: # run manually
    types: [check-link]

jobs:
  linkcheck:
    name: Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Check Links
        run: yarn lint:linkcheck | grep 'BROKEN'
