name: Broken Link Check

on:
  schedule:
    - cron: 0 0 1 * * # run monthly
  repository_dispatch: # run manually
    types: [check-link]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/github-actions-link-checker@v1.0.1
        with:
          # Required:
          url: "https://jasik.xyz"
          # optional:
          honorRobotExclusions: false
          ignorePatterns: "github,google"
          recursiveUrls: true # Check all urls on all reachable pages (could take a while)
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
