name: Lint

on:
  push:
    branches:
      - main
      - renovate/*
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
          with:
            node-version: '14'
            cache: 'yarn'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Install Dependencies
        run: yarn install --immutable

      #- name: Check Dependencies
      #  run: yarn lint:deps

      - name: Check JSDoc Types
        run: yarn lint:typecheck

      - name: Lint ESLint
        run: yarn lint:eslint

      - name: Lint Prettier
        run: yarn lint:prettier

      - name: Validate HTML
        run: yarn lint:html-validate

      - name: Spellcheck
        run: yarn lint:spellcheck

      #- name: Lint Changelog
      #  run: yarn lint:changelog

      #- name: Check Lock File
      #  run: yarn && echo "Listing changed files:" && git diff --name-only --exit-code && echo "No files changed during lint."
